# PRD environment overlay
global:
  environment: "PRD"

config:
  cluster: "bdc-workloads-prd-nv"
  datasources:
    victoriametrics:
      url: "http://vm-cluster-vmselect.monitoring:8481/select/0/prometheus"
    loki:
      url: "http://loki-gateway.monitoring:80"
    alertmanager:
      url: "http://prometheus-alertmanager.monitoring:9093"
  ml:
    enabled: true
  controller:
    jobInterval: "60s"
    cooldown: "5m"

controller:
  replicas: 2
  image:
    tag: ""
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      memory: 512Mi

worker:
  replicas: 3
  image:
    tag: ""
  resources:
    requests:
      cpu: 500m
      memory: 256Mi
    limits:
      memory: 1Gi

redis:
  persistence:
    size: 5Gi
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi

ml:
  enabled: true
  replicas: 2
  image:
    tag: ""
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      memory: 2Gi
