// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.4
// source: proto/ml.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MLDetector_Forecast_FullMethodName           = "/anomaly.MLDetector/Forecast"
	MLDetector_DetectMultivariate_FullMethodName = "/anomaly.MLDetector/DetectMultivariate"
	MLDetector_Health_FullMethodName             = "/anomaly.MLDetector/Health"
)

// MLDetectorClient is the client API for MLDetector service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MLDetectorClient interface {
	Forecast(ctx context.Context, in *ForecastRequest, opts ...grpc.CallOption) (*ForecastResponse, error)
	DetectMultivariate(ctx context.Context, in *MultivariateRequest, opts ...grpc.CallOption) (*MultivariateResponse, error)
	Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error)
}

type mLDetectorClient struct {
	cc grpc.ClientConnInterface
}

func NewMLDetectorClient(cc grpc.ClientConnInterface) MLDetectorClient {
	return &mLDetectorClient{cc}
}

func (c *mLDetectorClient) Forecast(ctx context.Context, in *ForecastRequest, opts ...grpc.CallOption) (*ForecastResponse, error) {
	out := new(ForecastResponse)
	err := c.cc.Invoke(ctx, MLDetector_Forecast_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLDetectorClient) DetectMultivariate(ctx context.Context, in *MultivariateRequest, opts ...grpc.CallOption) (*MultivariateResponse, error) {
	out := new(MultivariateResponse)
	err := c.cc.Invoke(ctx, MLDetector_DetectMultivariate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLDetectorClient) Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, MLDetector_Health_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MLDetectorServer is the server API for MLDetector service.
// All implementations must embed UnimplementedMLDetectorServer
// for forward compatibility
type MLDetectorServer interface {
	Forecast(context.Context, *ForecastRequest) (*ForecastResponse, error)
	DetectMultivariate(context.Context, *MultivariateRequest) (*MultivariateResponse, error)
	Health(context.Context, *Empty) (*HealthResponse, error)
	mustEmbedUnimplementedMLDetectorServer()
}

// UnimplementedMLDetectorServer must be embedded to have forward compatible implementations.
type UnimplementedMLDetectorServer struct {
}

func (UnimplementedMLDetectorServer) Forecast(context.Context, *ForecastRequest) (*ForecastResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Forecast not implemented")
}
func (UnimplementedMLDetectorServer) DetectMultivariate(context.Context, *MultivariateRequest) (*MultivariateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DetectMultivariate not implemented")
}
func (UnimplementedMLDetectorServer) Health(context.Context, *Empty) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedMLDetectorServer) mustEmbedUnimplementedMLDetectorServer() {}

// UnsafeMLDetectorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MLDetectorServer will
// result in compilation errors.
type UnsafeMLDetectorServer interface {
	mustEmbedUnimplementedMLDetectorServer()
}

func RegisterMLDetectorServer(s grpc.ServiceRegistrar, srv MLDetectorServer) {
	s.RegisterService(&MLDetector_ServiceDesc, srv)
}

func _MLDetector_Forecast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForecastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLDetectorServer).Forecast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLDetector_Forecast_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLDetectorServer).Forecast(ctx, req.(*ForecastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLDetector_DetectMultivariate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultivariateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLDetectorServer).DetectMultivariate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLDetector_DetectMultivariate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLDetectorServer).DetectMultivariate(ctx, req.(*MultivariateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLDetector_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLDetectorServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLDetector_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLDetectorServer).Health(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// MLDetector_ServiceDesc is the grpc.ServiceDesc for MLDetector service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MLDetector_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "anomaly.MLDetector",
	HandlerType: (*MLDetectorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Forecast",
			Handler:    _MLDetector_Forecast_Handler,
		},
		{
			MethodName: "DetectMultivariate",
			Handler:    _MLDetector_DetectMultivariate_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _MLDetector_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ml.proto",
}
