// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.31.1
// source: proto/worker.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	WorkerService_ProcessJobs_FullMethodName  = "/anomaly.WorkerService/ProcessJobs"
	WorkerService_ReportEvents_FullMethodName = "/anomaly.WorkerService/ReportEvents"
)

// WorkerServiceClient is the client API for WorkerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkerServiceClient interface {
	// ProcessJobs sends a batch of detection jobs to a worker.
	ProcessJobs(ctx context.Context, in *JobBatch, opts ...grpc.CallOption) (*JobResults, error)
	// ReportEvents is a server-streaming RPC where workers push K8s events to controller.
	ReportEvents(ctx context.Context, in *EventStreamRequest, opts ...grpc.CallOption) (WorkerService_ReportEventsClient, error)
}

type workerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerServiceClient(cc grpc.ClientConnInterface) WorkerServiceClient {
	return &workerServiceClient{cc}
}

func (c *workerServiceClient) ProcessJobs(ctx context.Context, in *JobBatch, opts ...grpc.CallOption) (*JobResults, error) {
	out := new(JobResults)
	err := c.cc.Invoke(ctx, WorkerService_ProcessJobs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) ReportEvents(ctx context.Context, in *EventStreamRequest, opts ...grpc.CallOption) (WorkerService_ReportEventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &WorkerService_ServiceDesc.Streams[0], WorkerService_ReportEvents_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &workerServiceReportEventsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type WorkerService_ReportEventsClient interface {
	Recv() (*EventReport, error)
	grpc.ClientStream
}

type workerServiceReportEventsClient struct {
	grpc.ClientStream
}

func (x *workerServiceReportEventsClient) Recv() (*EventReport, error) {
	m := new(EventReport)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// WorkerServiceServer is the server API for WorkerService service.
// All implementations must embed UnimplementedWorkerServiceServer
// for forward compatibility
type WorkerServiceServer interface {
	// ProcessJobs sends a batch of detection jobs to a worker.
	ProcessJobs(context.Context, *JobBatch) (*JobResults, error)
	// ReportEvents is a server-streaming RPC where workers push K8s events to controller.
	ReportEvents(*EventStreamRequest, WorkerService_ReportEventsServer) error
	mustEmbedUnimplementedWorkerServiceServer()
}

// UnimplementedWorkerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedWorkerServiceServer struct {
}

func (UnimplementedWorkerServiceServer) ProcessJobs(context.Context, *JobBatch) (*JobResults, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessJobs not implemented")
}
func (UnimplementedWorkerServiceServer) ReportEvents(*EventStreamRequest, WorkerService_ReportEventsServer) error {
	return status.Errorf(codes.Unimplemented, "method ReportEvents not implemented")
}
func (UnimplementedWorkerServiceServer) mustEmbedUnimplementedWorkerServiceServer() {}

// UnsafeWorkerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerServiceServer will
// result in compilation errors.
type UnsafeWorkerServiceServer interface {
	mustEmbedUnimplementedWorkerServiceServer()
}

func RegisterWorkerServiceServer(s grpc.ServiceRegistrar, srv WorkerServiceServer) {
	s.RegisterService(&WorkerService_ServiceDesc, srv)
}

func _WorkerService_ProcessJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).ProcessJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_ProcessJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).ProcessJobs(ctx, req.(*JobBatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_ReportEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EventStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkerServiceServer).ReportEvents(m, &workerServiceReportEventsServer{stream})
}

type WorkerService_ReportEventsServer interface {
	Send(*EventReport) error
	grpc.ServerStream
}

type workerServiceReportEventsServer struct {
	grpc.ServerStream
}

func (x *workerServiceReportEventsServer) Send(m *EventReport) error {
	return x.ServerStream.SendMsg(m)
}

// WorkerService_ServiceDesc is the grpc.ServiceDesc for WorkerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "anomaly.WorkerService",
	HandlerType: (*WorkerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessJobs",
			Handler:    _WorkerService_ProcessJobs_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReportEvents",
			Handler:       _WorkerService_ReportEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/worker.proto",
}
